---
- name: Enable amazon-linux-extras packages
  command: "amazon-linux-extras enable {{ item }}"
  args:
    creates: /etc/yum.repos.d/amzn2-extras.repo
  become: true
  when: ansible_distribution == "Amazon"
  with_items:
    - docker

- name: Install Packages
  package:
    name:
      - python
      - python-setuptools
      - docker
    state: latest

- name: Install Pip
  easy_install:
    name: pip
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Download and Install Pip
  block:
    - name: Download Pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py
    - name: Install Pip
      command: "python /tmp/get-pip.py"
      args:
        creates: /usr/bin/pip
  become: true
  when: ansible_distribution == "Amazon"

- name: docker config
  lineinfile:
    path: /etc/sysconfig/docker
    line: 'OPTIONS="--log-driver=json-file --log-opt max-size=50m --log-opt max-file=1 --default-ulimit nofile=4096:65535 --bip=172.17.42.1/16 --mtu=9001"'
    regexp: '^OPTIONS'
    state: present

- name: dangling volumes cron
  copy:
    src: docker-gc-dangling-volumes.sh
    dest: /etc/cron.hourly/
    mode: 0755

- name: python docker
  pip:
    name: docker
