---
name: Deploy to Ansible Galaxy
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            ansible
            ansible-lint
            molecule
            molecule-docker
            testinfra
            docker
            flake8
            yamllint
      - run: ansible --version
      - run: printf '[defaults]\nroles_path=../' >ansible.cfg
      - run: molecule test
      - run: ansible-galaxy role import --token ${{ secrets.ANSIBLE_GALAXY_TOKEN }}  mergermarket ${{ github.event.repository.name }}
